version: '2.2'
services:
  jmeter_master:
    build: .
    entrypoint: bin/jmeter -n -t /jmeter_scripts/script.jmx -R dockerjmetercluster_jmeter_slave_1,dockerjmetercluster_jmeter_slave_2
    # entrypoint: sleep 9999
    volumes: 
      - ./jmeter_scripts:/jmeter_scripts/:ro
      - ./jmeter_results:/jmeter_results/
    depends_on: 
      - jmeter_slave
  jmeter_slave:
    build: .
    scale: 2
    entrypoint: bin/jmeter-server
    